name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Debug
      BUILD_DIR: ${{github.workspace}}/build
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B "$BUILD_DIR"

    - name: Build
      run: cmake --build "$BUILD_DIR" --config $CMAKE_BUILD_TYPE

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: ctest --config $CMAKE_BUILD_TYPE --output-on-failure
